### YamlMime:Lifecycle
metadata:
  title: Virtualizace aplikací společnosti Microsoft 5.1
  description: Virtualizace aplikací společnosti Microsoft 5.1 se řídí zásadami pevného životního cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "850782"
name: Virtualizace aplikací společnosti Microsoft 5.1
summary: >+
  Virtualizace aplikací společnosti Microsoft 5.1 se řídí [zásadami pevného](/lifecycle/policies/fixed) životního cyklu.


  To platí pro následující edice: pro službu Vzdálená plocha, pro stolní počítače se systémem Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informace o produktu](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Edice \n* pro vzdálenou plochu\n* pro plochy systému Windows"
