### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Nástroj Microsoft System Center Configuration Manager 2007 R2 se řídí pevnými zásadami životního cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: dc120aa48cf00c559b79cd24b31cde9a8122b573
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4106223"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Nástroj Microsoft System Center Configuration manager 2007 R2 se řídí [pevnými](/lifecycle/policies/fixed) zásadami životního cyklu.



  > [!IMPORTANT]

  > Podpora tohoto produktu skončila. Pokyny k migraci naleznete níže.
products:
- msc
policyType: fixed
supportDates:
  start: 2008-11-29T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2008-11-29T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Odkazy \n* [Návod k migraci](/mem/configmgr/core/migration/planning-for-migration)\n* [Další pokyny pro migraci](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
