### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 se řídí pevnými zásadami životního cyklu.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Windows Desktops,Sequencer
  ms.openlocfilehash: fb533aa91b47539b019872143dbfa2fcdd3d5cb0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4127683"
name: Microsoft Application Virtualization 4.6
summary: >+
  Microsoft Application Virtualization 4.6 se řídí [pevnými](/lifecycle/policies/fixed) zásadami životního cyklu.


  To platí pro následující edice: for Remote Desktop Services, for Windows Desktops, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informace o produktu a migraci](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Návod k migraci](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Zásady aktualizace Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Protože klient App-V 4.6 využívá server App-V 4.5, bude server App-V 4.5 nadále podporován podle dat životního cyklu aplikace App-V 4.6 při použití s podporovaným klientem App-V 4.6.\n\n## <a name=\"editions\"></a>Edice \n* for Remote Desktop Services\n* pro Windows Desktops\n* Sequencer"
