### YamlMime:Lifecycle
metadata:
  title: Virtualizace aplikací 4.6 společnosti Microsoft hostující pro stolní počítače systému Windows
  description: Microsoft Application Virtualization Hosting 4.6 pro Windows Desktops se řídí pevnými zásadami životního cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "809988"
name: Virtualizace aplikací 4.6 společnosti Microsoft hostující pro stolní počítače systému Windows
summary: >+
  Microsoft Application Virtualization Hosting 4.6 pro Windows Desktops se řídí [pevnými](/lifecycle/policies/fixed) zásadami životního cyklu.


  To platí pro následující edice: pro Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informace o produktu a migraci](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Zásady aktualizace Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Protože klient App-V 4.6 využívá server App-V 4.5, bude server App-V 4.5 nadále podporován podle dat životního cyklu aplikace App-V 4.6 při použití s podporovaným klientem App-V 4.6.\n\n## <a name=\"editions\"></a>Edice \n* pro Windows Desktops"
