### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 pro Windows Desktops
  description: Microsoft Application Virtualization Hosting 5.1 pro Windows Desktops se řídí pevnými zásadami životního cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "850964"
name: Microsoft Application Virtualization Hosting 5.1 pro Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 5.1 pro Windows Desktops se řídí [pevnými](/lifecycle/policies/fixed) zásadami životního cyklu.


  To platí pro následující edice: pro Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informace o produktu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Edice \n* pro Windows Desktops"
