### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security dodržuje zásady pro fixní životnost.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924248"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security dodržuje zásady pro [fixní](/lifecycle/policies/fixed) životnost.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Odkazy \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security byl zastaven z července 14th, 2015. Aktualizace definic malwaru a antispywaru nebudou po skončení podpory pro verzi produktu nadále k dispozici. Vyhodnoťte ochranu koncového bodu System Center jako náhradu."
