### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security dodržuje zásady pro fixní životnost.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908670"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security dodržuje zásady pro [fixní](/lifecycle/policies/fixed) životnost.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Odkazy \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security byl ukončen. Podpora končí 14th, 2015. Aktualizace definic malwaru a antispywaru nebudou po skončení podpory pro verzi produktu nadále k dispozici. Vyhodnoťte ochranu koncového bodu System Center jako náhradu."
