### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager (LTSB - verze 1606)
  description: Microsoft System Center Configuration Manager (LTSB - verze 1606) se řídí pevnými zásadami životního cyklu.
  ms.date: 08/20/2020
  ms.openlocfilehash: 606034d7f3694f3e06a47bdc5e1a45561102c238
  ms.sourcegitcommit: f5095aa6fc41dcc71c883cae08719b5b6bf9585c
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 08/20/2020
  ms.locfileid: "905796"
name: Microsoft System Center Configuration Manager (LTSB - verze 1606)
summary: >+
  Microsoft System Center Configuration Manager (LTSB - verze 1606) se řídí [Pevnými](/lifecycle/policies/fixed) zásadami životního cyklu.


products:
- m365
policyType: fixed
supportDates:
  start: 10/12/2016
  end: 10/12/2021
  extendedEnd: 01/12/2027
releases:
- version: Original Release
  startDate: 10/12/2016
  endDate: 01/12/2027
content: "\n## <a name=\"links\"></a>Odkazy \n* [Informace o servisu a podpoře](/sccm/core/understand/learn-more-editions)"
