### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration manager 2007 R3 se řídí pevnými zásadami životního cyklu.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Nástroj Microsoft System Center Configuration Manager 2007 R3 se řídí [pevnými](/lifecycle/policies/fixed) zásadami životního cyklu.


  > [!IMPORTANT]
  > Podpora tohoto produktu skončila. Pokyny k migraci naleznete níže.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Odkazy 
  * [Návod k migraci](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Další pokyny pro migraci](/mem/configmgr/core/migration/planning-for-migration)