### YamlMime:Lifecycle
metadata:
  title: Virtualizace aplikací SoftGrid
  description: Virtualizace aplikací SoftGrid se řídí zásadami pevného životního cyklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "809290"
name: Virtualizace aplikací SoftGrid
summary: >
  Virtualizace aplikací SoftGrid se řídí zásadami [pevného](/lifecycle/policies/fixed) životního cyklu.


  Toto se vztahuje na následující edice: 4.1 pro stolní počítače, 4.2 pro stolní počítače, 4.1 pro terminálové služby


  > [!IMPORTANT]

  > Podpora je ukončena. Pokyny k migraci naleznete níže.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Odkazy \n* [Návod k migraci](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Edice \n* 4.1 pro stolní počítače\n* 4.2 pro stolní počítače\n* 4.1 pro terminálové služby"
