### YamlMime:Lifecycle
metadata:
  title: Virtualizace aplikací SoftGrid
  description: Virtualizace aplikací SoftGrid se řídí zásadami pevného životního cyklu.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 6b63a556c63bca08045d0335bd9233a0ae07a878
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4119839"
name: Virtualizace aplikací SoftGrid
summary: >
  Virtualizace aplikací SoftGrid se řídí zásadami [pevného](/lifecycle/policies/fixed) životního cyklu.


  Toto se vztahuje na následující edice: 4.1 pro stolní počítače, 4.2 pro stolní počítače, 4.1 pro terminálové služby


  > [!IMPORTANT]

  > Podpora je ukončena. Pokyny k migraci naleznete níže.
products:
- windows
policyType: fixed
supportDates:
  start: 2007-05-25T00:00:00.000-08:00
  end: 2012-07-10T22:59:59.999-08:00
  extendedEnd: 2017-07-11T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-05-25T00:00:00.000-08:00
  endDate: 2017-07-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Odkazy \n* [Návod k migraci](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Edice \n* 4.1 pro stolní počítače\n* 4.2 pro stolní počítače\n* 4.1 pro terminálové služby"
