### YamlMime:Lifecycle
metadata:
  title: Whale Communications Intelligent Application Gateway
  description: Whale Communications Intelligent Application Gateway se řídí pevnými zásadami životního cyklu.
  ms.date: 08/21/2020
  ms.openlocfilehash: 24af584653eafe614a9dd064d02e63f59ef5665a
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4105261"
name: Whale Communications Intelligent Application Gateway
summary: >+
  Whale Communications Intelligent Application Gateway se řídí [Pevnými](/lifecycle/policies/fixed) zásadami životního cyklu.


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 2007-10-10T00:00:00.000-08:00
  end: 2010-07-13T22:59:59.999-08:00
releases:
- version: "3.1"
  startDate: 2007-10-10T00:00:00.000-08:00
  endDate: 2008-07-08T22:59:59.999-08:00
- version: "3.6"
  startDate: 2007-10-10T00:00:00.000-08:00
  endDate: 2010-07-13T22:59:59.999-08:00
content: "\n\n> [!NOTE]\n> Podpora pro tento produkt se řídí podmínkami platnými při jeho nákupu."
