### YamlMime:Lifecycle
metadata:
  title: Inteligentní brána aplikace Whale Communications
  description: Inteligentní brána Whale komunikace se řídí zásadami fixní životnosti.
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907133"
name: Inteligentní brána aplikace Whale Communications
summary: >+
  Inteligentní brána Whale komunikace se řídí zásadami [fixní](/lifecycle/policies/fixed) životnosti.


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> Podpora pro tento produkt se řídí podmínkami platnými při jeho nákupu."
